#include<iostream>
#include<vector>
#include<stdlib.h>
#include<string.h>
#include<stack>
#include<assert.h>
#include<utility>
#include<queue>

using namespace std;

#include"FindInArray.h"
#include"ReplaceSpace.h"
//#include"PrintListFromTailToHead.h"
//#include"ReConstructBinaryTree.h"
#include"QueueWithTwoStack.h"
//#include"MergeList.h"
#include"SumSolution.h"
//#include"ReverseList.h"
//#include"FindKthToTail.h"
#include"Add.h"
#include"MinNumberInRotateArray.h"
//#include"EntryNodeOfLoop.h"
#include"Fibonacci.h"
#include"JumpFloor.h"
#include"DelNode.h"
#include"JumpFloorII.h"
#include"RectCover.h"
#include"StackWithTwoQueue.h"
#include"MinStack.h"
#include"IsPopOrder.h"
#include"NumberOf1.h"
//#include"PrintLevelTree.h"
#include"Power.h"
#include"ReOrderArray.h"
//#include"HasSubtree.h"
//#include"Mirror.h"
#include"PrintMatrix.h"
#include"VerifySquenceOfBST.h"
//#include"FindPath.h"
#include"RandomClone.h"
#include"Convert.h"

int main()
{
	//TestFindInArray();
	//TestRepalceSpace();
	//TestprintListFromTailToHead();
	//TestReConstructBinaryTree();
	//TestQueueWithTwoStack();
	//TestMergeList();
	//TestSumSolution();
	//TestReverseList();
	//TestFindKthToTail();
	//TestAdd();
	//TestMinNumberInRotateArray();
	//TestEntryNodeOfLoop();
	//TestFibonacci();
	//TestJumpFloor();
	//TestDelNode();
	//TestJumpFloorII();
	//TestRectCover();
	//TestStackWithTwoQueue();
	//TestMinStack();
	//TestIsPopOrder();
	//TestNumberOf1();
	//TestPrintLevelTree();
	//TestPower();
	//TestReOrderArray();
	//TestHasSubtree();
	//TestMirror();
	//TestPrintMatrix();
	//TestVerifySquenceOfBST();
	//TestFindPath();
	//TestRandomClone();
	TestConvert();

	return 0;
}